window.PRODUCTS_SEED = [
  {
    "master_sku": "L3-B-BR-TR-3",
    "amazon_sku": "SW-TR-BL-BR-3",
    "flipkart_sku": "SW-TR-BL-BR-3",
    "website_sku": "3L-B-BR-TR-3",
    "amazon_asin": "B0FPM59XH7",
    "flipkart_fsn": "BDDHG2HVKHHFBGH5",
    "product_family": "Xyra",
    "product_description": "Boston-Ortho Tri-Brown-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-TR-3",
    "amazon_sku": "SW-TR-BL-BL-3",
    "flipkart_sku": "HT-SB-B-TR-3x6",
    "website_sku": "SW-TR-BL-BL-3",
    "amazon_asin": "B0F32PBLQG",
    "flipkart_fsn": "BDDH9EZYPFE99PNH",
    "product_family": "Xyra",
    "product_description": "Xyra-Ortho Tri-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "HT-SPC-5LY-B-FW",
    "amazon_sku": "HT-SPC-5LY-B-FW",
    "flipkart_sku": "HT-SPC-5LY-B-FW",
    "website_sku": "HT-SPC-5LY-B-FW",
    "amazon_asin": "B0FFBMB5KB",
    "flipkart_fsn": "Not Listed",
    "product_family": "Spacio",
    "product_description": "Spacio-Black-Frosty White",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "HT-SPC-5LY-B-AO",
    "amazon_sku": "HT-SPC-5LY-B-AO",
    "flipkart_sku": "HT-SPC-5LY-B-AO",
    "website_sku": "HT-SPC-5LY-B-AO",
    "amazon_asin": "B0FCMT97BF",
    "flipkart_fsn": "Not Listed",
    "product_family": "Spacio",
    "product_description": "Spacio-Black-Walnut",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-HB-6",
    "amazon_sku": "HT-KBM-HB-6x6.25",
    "flipkart_sku": "HT-KBM-HB-6x6.25",
    "website_sku": "King Square HB (M) 6",
    "amazon_asin": "B0DSPJYM38",
    "flipkart_fsn": "BDDH8APMNJPJCKCM",
    "product_family": "Samos",
    "product_description": "Samos-Metal-Black-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-HB-5",
    "amazon_sku": "HT-QBM-HB-5x6.25",
    "flipkart_sku": "HT-QBM-HB-5x6.25",
    "website_sku": "Queen Square HB(M) 5",
    "amazon_asin": "B0D9HMKGNS",
    "flipkart_fsn": "BDDH2W7QN77UGHA2",
    "product_family": "Samos",
    "product_description": "Samos-Metal-Black-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-HB-4",
    "amazon_sku": "HT-DBM-HB-4x6",
    "flipkart_sku": "HT-DBM-HB-4x6",
    "website_sku": "Double Square HB (M) 4",
    "amazon_asin": "B0D3TGKG4J",
    "flipkart_fsn": "BDDHYRGTSHUJSTT2",
    "product_family": "Samos",
    "product_description": "Samos-Metal-Black-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HB-6",
    "amazon_sku": "HT-KB-HB-6x6.25",
    "flipkart_sku": "HT-KB-HB-6x6.25",
    "website_sku": "King Square HB 6",
    "amazon_asin": "B0DSPJ2K72",
    "flipkart_fsn": "BDDH8APMPGYSGMD4",
    "product_family": "Samos",
    "product_description": "Samos-Metal-Black-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HB-5",
    "amazon_sku": "HT-QB-HB-5x6.25",
    "flipkart_sku": "HT-QB-HB-5x6.25",
    "website_sku": "Queen Square HB 5",
    "amazon_asin": "B0D9HNRFQV",
    "flipkart_fsn": "BDDH2W7WHQ69BPMM",
    "product_family": "Samos",
    "product_description": "Samos-Double layer-Black-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HB-4",
    "amazon_sku": "HT-DB-HB-4x6",
    "flipkart_sku": "HT-DB-HB-4x6",
    "website_sku": "Double Square HB 4",
    "amazon_asin": "B0D3TGLS91",
    "flipkart_fsn": "BDDH2D84RHUZSHBS",
    "product_family": "Samos",
    "product_description": "Samos-Double layer-Black-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-GR-RE-3",
    "amazon_sku": "HT-3L-SB-B-GR-RE-3x6",
    "flipkart_sku": "HT-3L-SB-B-GR-RE-3x6",
    "website_sku": "HT-3L-SB-B-GR-RE-3x6",
    "amazon_asin": "B0GMXX2YC6",
    "flipkart_fsn": "BDDHKHPYJ3JMJKPG",
    "product_family": "Rollease",
    "product_description": "Rollease-Ortho Tri-Black-3X6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-OS-5",
    "amazon_sku": "HT-M-QB-B-OS-5x6",
    "flipkart_sku": "HT-M-QB-B-OS-5x6",
    "website_sku": "HT-M-QB-B-OS-5x6",
    "amazon_asin": "B0FS1VQ17L",
    "flipkart_fsn": "BDDHG99ARKZ6VFYC",
    "product_family": "Oslo",
    "product_description": "Oslo-Metal-Black-5X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-OS-4",
    "amazon_sku": "HT-M-DB-B-OS-4x6",
    "flipkart_sku": "HT-M-DB-B-OS-4x6",
    "website_sku": "HT-M-DB-B-OS-4x6",
    "amazon_asin": "B0GF94S3DF",
    "flipkart_fsn": "BDDHJZHBTEYGYHQR",
    "product_family": "Oslo",
    "product_description": "Oslo-Metal-Black-4X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-OS-5",
    "amazon_sku": "HT-2L-QB-B-OS-5x6",
    "flipkart_sku": "HT-2L-QB-B-OS-5x6",
    "website_sku": "HT-2L-QB-B-OS-5x6",
    "amazon_asin": "B0FS1Y2RN5",
    "flipkart_fsn": "BDDHJGVGHYCTD7PY",
    "product_family": "Oslo",
    "product_description": "Oslo-Double Layer-Black-5X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-OS-4",
    "amazon_sku": "HT-2L-DB-B-OS-4x6",
    "flipkart_sku": "HT-2L-DB-B-OS-4x6",
    "website_sku": "HT-2L-DB-B-OS-4x6",
    "amazon_asin": "B0GF8VXSYC",
    "flipkart_fsn": "BDDHJK5XNNEQHNZX",
    "product_family": "Oslo",
    "product_description": "Oslo-Double Layer-Black-4X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-W-BL-EL-3",
    "amazon_sku": "HT-MB-W-HB(EL)-36",
    "flipkart_sku": "HT-MB-W-HB(EL)-36",
    "website_sku": "HT-MB-W-HB(EL)-36",
    "amazon_asin": "B0D6NC5C1F",
    "flipkart_fsn": "BDDH8BPCRHUGHUDW",
    "product_family": "Nova",
    "product_description": "Nova- Metal-White- 3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-IV-BL-EL-6",
    "amazon_sku": "HT-M-KBM-IV-EL-6x6.25",
    "flipkart_sku": "HT-M-KBM-IV-EL-6x6.25",
    "website_sku": "M-IV-BL-EL-6",
    "amazon_asin": "B0FBM9S113",
    "flipkart_fsn": "BDDHEHZSDKCFEHYD",
    "product_family": "Nova",
    "product_description": "Nova-Metal-White-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-IV-BL-EL-5",
    "amazon_sku": "HT-M-QBM-IV-EL-5x6.25",
    "flipkart_sku": "HT-M-QBM-IV-EL-5x6.25",
    "website_sku": "M-IV-BL-EL-5",
    "amazon_asin": "B0F9VGBXLT",
    "flipkart_fsn": "BDDHCHYQ27ZDRSHX",
    "product_family": "Nova",
    "product_description": "Nova-Metal-White-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-IV-BL-EL-4",
    "amazon_sku": "HT-M-DBM-IV-EL-4x6.25",
    "flipkart_sku": "HT-M-DBM-IV-EL-4x6.25",
    "website_sku": "M-IV-BL-EL-4",
    "amazon_asin": "B0FBX2R62B",
    "flipkart_fsn": "BDDHEHYHDDMZYMYJ",
    "product_family": "Nova",
    "product_description": "Nova-Metal-White-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-EL-6",
    "amazon_sku": "HT-KBM-EL-6x6",
    "flipkart_sku": "HT-KBM-EL-6x6",
    "website_sku": "King Round EL (M) 6",
    "amazon_asin": "B0DCCCLMMV",
    "flipkart_fsn": "BDDH3KFWMF6RF5NM",
    "product_family": "Nova",
    "product_description": "Nova-Metal-Black-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-EL-5",
    "amazon_sku": "HT-QBM-EL-5x6",
    "flipkart_sku": "HT-QBM-EL-5x6",
    "website_sku": "Queen Round EL(M) 5",
    "amazon_asin": "B0CPFVF2LF",
    "flipkart_fsn": "BDDGVYAHWXSD6HY9",
    "product_family": "Nova",
    "product_description": "Nova-Metal-Black-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-EL-4",
    "amazon_sku": "HT-DBM-EL-4x6",
    "flipkart_sku": "HT-DBM-EL-4x6",
    "website_sku": "Double Round EL (M) 4",
    "amazon_asin": "B0C6F83BXZ",
    "flipkart_fsn": "BDDGQ43N7BCXAEGZ",
    "product_family": "Nova",
    "product_description": "Nova-Metal-Black-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-EL-3",
    "amazon_sku": "HT-MB-B-HB(EL)-36",
    "flipkart_sku": "HT-MB-B-HB(EL)-36",
    "website_sku": "HT-MB-B-HB(EL)-36",
    "amazon_asin": "B0D6NBJ3WH",
    "flipkart_fsn": "BDDH28QZEZP6PT6F",
    "product_family": "Nova",
    "product_description": "Nova- Metal- Black- 3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-W-BL-EL-3",
    "amazon_sku": "HT-R-W-B-HB(EL)-2IN(3L)-36",
    "flipkart_sku": "HT-R-W-B-HB(EL)-2IN(3L)-36",
    "website_sku": "HT-R-W-B-HB(EL)-2IN(3L)-36",
    "amazon_asin": "B0DQL25S1X",
    "flipkart_fsn": "BDDHDCSBGZYCNZMP",
    "product_family": "Nova",
    "product_description": "Nova-Ortho Tri-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-EL-6",
    "amazon_sku": "HT-3L-KB-B-BL-NV-6",
    "flipkart_sku": "HT-3L-KB-B-BL-NV-6",
    "website_sku": "HT-3L-KB-B-BL-NV-6",
    "amazon_asin": "B0GRP24264",
    "flipkart_fsn": "BDDHHAETFZG3YBYF",
    "product_family": "Nova",
    "product_description": "Nova-Ortho Tri layer-Black-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-EL-5",
    "amazon_sku": "HT-3L-QB-B-BL-NV-5",
    "flipkart_sku": "HT-3L-QB-B-BL-NV-5",
    "website_sku": "HT-3L-QB-B-BL-NV-5",
    "amazon_asin": "B0GRNMDHTX",
    "flipkart_fsn": "BDDHHAEFYDPUTMPJ",
    "product_family": "Nova",
    "product_description": "Nova-Ortho Tri layer-Black-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-EL-4",
    "amazon_sku": "HT-3L-DB-B-BL-NV-4",
    "flipkart_sku": "HT-3L-DB-B-BL-NV-4",
    "website_sku": "HT-3L-DB-B-BL-NV-4",
    "amazon_asin": "B0GRJ8VZ4B",
    "flipkart_fsn": "BDDHHADGRGNP364X",
    "product_family": "Nova",
    "product_description": "Nova-Ortho Tri layer-Black-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-EL-3",
    "amazon_sku": "HT-R-B-B-HB(EL)-2IN(3L)-36",
    "flipkart_sku": "HT-R-B-B-HB(EL)-2IN(3L)-36",
    "website_sku": "HT-R-B-B-HB(EL)-2IN(3L)-36",
    "amazon_asin": "B0DQKZT5V3",
    "flipkart_fsn": "BDDHDCMZEZ54SD9P",
    "product_family": "Nova",
    "product_description": "Nova-Ortho Tri-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BL-EL-3",
    "amazon_sku": "HT-R-W-B-HB(EL)-2IN-36",
    "flipkart_sku": "HT-R-W-B-HB(EL)-2IN-36",
    "website_sku": "HT-R-W-B-HB(EL)-2IN-36",
    "amazon_asin": "B0D87579B4",
    "flipkart_fsn": "BDDHKBH24JXGHDQU",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-IV-BL-EL-6",
    "amazon_sku": "HT-2L-KB-IV-EL-6x6.25",
    "flipkart_sku": "HT-2L-KB-IV-EL-6x6.25",
    "website_sku": "2L-IV-BL-EL-6",
    "amazon_asin": "B0FBMGPSWQ",
    "flipkart_fsn": "BDDHEHZKH7WCF6SJ",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-White-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-IV-BL-EL-5",
    "amazon_sku": "HT-2L-QB-IV-EL-5x6.25",
    "flipkart_sku": "HT-2L-QB-IV-EL-5x6.25",
    "website_sku": "2L-IV-BL-EL-5",
    "amazon_asin": "B0F9VGVQ6Y",
    "flipkart_fsn": "BDDHCHYQTJ96HSFS",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-White-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-IV-BL-EL-4",
    "amazon_sku": "HT-2L-DB-IV-EL-4x6.25",
    "flipkart_sku": "HT-2L-DB-IV-EL-4x6.25",
    "website_sku": "2L-IV-BL-EL-4",
    "amazon_asin": "B0F9VGVQ6W",
    "flipkart_fsn": "BDDHCHYQCYGV8NGU",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-White-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-EL-6",
    "amazon_sku": "HT-KB-EL-6x6",
    "flipkart_sku": "HT-KB-EL-6x6",
    "website_sku": "King Round EL 6",
    "amazon_asin": "B0DCC8C1XH",
    "flipkart_fsn": "BDDH3KHYVZZZVKJJ",
    "product_family": "Nova",
    "product_description": "Nova-Double Layer-Black-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-EL-5",
    "amazon_sku": "HT-QB-EL-5x6",
    "flipkart_sku": "HT-QB-EL-5x6",
    "website_sku": "Queen Round EL 5",
    "amazon_asin": "B0CPFT6698",
    "flipkart_fsn": "BDDGVYB3ACHUZCSY",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-Black-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-EL-4",
    "amazon_sku": "HT-DB-EL-4x6",
    "flipkart_sku": "HT-DB-EL-B-4x6",
    "website_sku": "Double Round EL 4",
    "amazon_asin": "B0BWS1QCYZ",
    "flipkart_fsn": "BDDGNF4CDFUWHU39",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-Black-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-EL-3",
    "amazon_sku": "HT-R-B-B-HB(EL)-2IN-36",
    "flipkart_sku": "HT-R-B-B-HB(EL)-2IN-36",
    "website_sku": "HT-R-B-B-HB(EL)-2IN-36",
    "amazon_asin": "B0D872MCRW",
    "flipkart_fsn": "BDDH28P2FXCWFM4A",
    "product_family": "Nova",
    "product_description": "Nova-Double layer-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BL-EL-3",
    "amazon_sku": "HT-R-W-B-HB(EL)-1IN-36",
    "flipkart_sku": "HT-R-W-B-HB(EL)-1IN-36",
    "website_sku": "HT-R-W-B-HB(EL)-1IN-36",
    "amazon_asin": "B0D86ZBYFD",
    "flipkart_fsn": "BDDHE8UBADCZBCPG",
    "product_family": "Nova",
    "product_description": "Nova-Single layer-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BL-EL-3",
    "amazon_sku": "HT-R-B-B-HB(EL)-1IN-36",
    "flipkart_sku": "HT-R-B-B-HB(EL)-1IN-36",
    "website_sku": "HT-R-B-B-HB(EL)-1IN-36",
    "amazon_asin": "B0D86YQQD4",
    "flipkart_fsn": "BDDH2GJGQGHJGRPG",
    "product_family": "Nova",
    "product_description": "Nova-Single layer-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BL-RX-3",
    "amazon_sku": "HTMR-3x6(WHITE)",
    "flipkart_sku": "HT-R-B-36",
    "website_sku": "1in Square(W) 3",
    "amazon_asin": "B09K9M5LQG",
    "flipkart_fsn": "BDDG8HY35WZ3XWCD",
    "product_family": "Nexon",
    "product_description": "Nexon-Single Layer-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BL-RX-2",
    "amazon_sku": "HTMR-2.5x6(WHITE)",
    "flipkart_sku": "HT-R-W-256",
    "website_sku": "1in Square(W) 2.5",
    "amazon_asin": "B09K91HT6X",
    "flipkart_fsn": "BDDGACYYNUCHH5RE",
    "product_family": "Nexon",
    "product_description": "Nexon-Single Layer-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BL-RX- 3",
    "amazon_sku": "HTMR-3x6(BLACK)",
    "flipkart_sku": "MBR-3X6",
    "website_sku": "1in Square(B) 3",
    "amazon_asin": "B098YS2BLQ",
    "flipkart_fsn": "BDDG4S9VGWHCUF92",
    "product_family": "Nexon",
    "product_description": "Nexon-Single Layer-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BL-RX- 2",
    "amazon_sku": "HTMR-2.5x6(BLACK)",
    "flipkart_sku": "MBR-2.5X6",
    "website_sku": "1in Square(B) 2.5",
    "amazon_asin": "B098Z6HVCC",
    "flipkart_fsn": "BDDG4SB4CHENGEZX",
    "product_family": "Nexon",
    "product_description": "Nexon-Single Layer-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-NS-5",
    "amazon_sku": "HT-M-QBM-B-NS-5x6.25",
    "flipkart_sku": "HT-M-QB-B-NS-5x6.25",
    "website_sku": "HT-M-QBM-B-NS-5x6.25",
    "amazon_asin": "B0F9Y9MDLR",
    "flipkart_fsn": "BDDHE6GZ5ZHSNHZK",
    "product_family": "Nesto",
    "product_description": "Nesto-Metal-Black-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-NS-4",
    "amazon_sku": "HT-M-DBM-B-NS-4x6.25",
    "flipkart_sku": "HT-M-DBM-B-NS-4x6.25",
    "website_sku": "M-B-BL-NS-4",
    "amazon_asin": "B0F9WQ7HFG",
    "flipkart_fsn": "BDDHCHFGW4QQG93K",
    "product_family": "Nesto",
    "product_description": "Nesto-Metal-Black-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-FW3-5",
    "amazon_sku": "SW-B-BL-FW3-5",
    "flipkart_sku": "HT-QB-B-FW3-WM-5x6",
    "website_sku": "HT-QB-B-FW3-WM-5x6",
    "amazon_asin": "B0F3XTX7W3",
    "flipkart_fsn": "BDDHCBF79SY75WVX",
    "product_family": "Luvo",
    "product_description": "Luvo-Metal-Wenge Black-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-FW2-5",
    "amazon_sku": "SW-B-BL-FW2-5",
    "flipkart_sku": "HT-QB-B-FW2-WM-5x6",
    "website_sku": "HT-QB-B-FW2-WM-5x6",
    "amazon_asin": "B0F3XSXKJK",
    "flipkart_fsn": "BDDH9ZKHKSWZD2FD",
    "product_family": "Luvo",
    "product_description": "Luvo-Metal-Stone Grain-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-FW1-5",
    "amazon_sku": "SW-B-BL-FW1-5",
    "flipkart_sku": "HT-QB-B-FW1-WM-5x6",
    "website_sku": "HT-QB-B-FW1-WM-5x6",
    "amazon_asin": "B0F3XTG9WL",
    "flipkart_fsn": "BDDH9ZKHAEW6GWBT",
    "product_family": "Luvo",
    "product_description": "Luvo-Metal-American Oak-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-FW3-5",
    "amazon_sku": "SW-3L-B-BL-FW3-5",
    "flipkart_sku": "HT-QB-3L-B-FW3-WM-5x6",
    "website_sku": "3L-B-BL-FW3-5",
    "amazon_asin": "B0F93J6XCD",
    "flipkart_fsn": "BDDHCC6TJYGJYZD7",
    "product_family": "Luvo",
    "product_description": "Luvo-Ortho Tri-Wenge Black-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-FW2-5",
    "amazon_sku": "SW-3L-B-BL-FW2-5",
    "flipkart_sku": "HT-QB-3L-B-FW2-WM-5x6",
    "website_sku": "3L-B-BL-FW2-5",
    "amazon_asin": "B0F93HTD7K",
    "flipkart_fsn": "BDDHCC6TBFQGHAG4",
    "product_family": "Luvo",
    "product_description": "Luvo-Ortho Tri-Stone Grain-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-FW1-5",
    "amazon_sku": "SW-3L-B-BL-FW1-5",
    "flipkart_sku": "HT-QB-3L-B-FW1-WM-5x6",
    "website_sku": "3L-B-BL-FW1-5",
    "amazon_asin": "B0F93LCZCD",
    "flipkart_fsn": "BDDHCC6TTEZXHD27",
    "product_family": "Luvo",
    "product_description": "Luvo-Ortho Tri-American Oak-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-FW3-5",
    "amazon_sku": "SW-2L-B-BL-FW3-5",
    "flipkart_sku": "SW-2L-B-BL-FW3-5",
    "website_sku": "2L-B-BL-FW3-5",
    "amazon_asin": "B0F93K8TX6",
    "flipkart_fsn": "BDDHEPPRRDCYR4ZA",
    "product_family": "Luvo",
    "product_description": "Luvo-Double Layer-Wenge Black-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-FW2-5",
    "amazon_sku": "SW-2L-B-BL-FW2-5",
    "flipkart_sku": "SW-2L-B-BL-FW2-5",
    "website_sku": "2L-B-BL-FW2-5",
    "amazon_asin": "B0F93K1728",
    "flipkart_fsn": "BDDHEPNKY3RV5KX9",
    "product_family": "Luvo",
    "product_description": "Luvo-Double Layer-Stone Grain-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-FW1-5",
    "amazon_sku": "SW-2L-B-BL-FW1-5",
    "flipkart_sku": "SW-2L-B-BL-FW1-5",
    "website_sku": "2L-B-BL-FW1-5",
    "amazon_asin": "B0F93KYTHV",
    "flipkart_fsn": "BDDHEHVPJUZZSBBC",
    "product_family": "Luvo",
    "product_description": "Luvo-Double Layer-American Oak-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-WH-LZ",
    "amazon_sku": "HT-D-W-WH-LZ-4",
    "flipkart_sku": "HT-D-W-WH-LZ-4",
    "website_sku": "HT-D-W-WH-LZ-4",
    "amazon_asin": "B0FY2T9Z3R",
    "flipkart_fsn": "CPTHKE3JZS3HPS4F",
    "product_family": "Lizon",
    "product_description": "Lizon-White-White",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-NH-LZ",
    "amazon_sku": "HT-D-W-NH-LZ-4",
    "flipkart_sku": "SW-D-W-NH-LZ-4",
    "website_sku": "HT-D-W-NH-LZ-4",
    "amazon_asin": "B0GPQ19RLH",
    "flipkart_fsn": "CPTHHPYHJECK9N5H",
    "product_family": "Lizon",
    "product_description": "Lizon-White-Natural Ash",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-GR-LZ",
    "amazon_sku": "HT-D-W-GR-LZ-4",
    "flipkart_sku": "HT-D-W-GR-LZ-4",
    "website_sku": "HT-D-W-GR-LZ-4",
    "amazon_asin": "B0FY2S3TLZ",
    "flipkart_fsn": "CPTHKE3JJQKUFTWV",
    "product_family": "Lizon",
    "product_description": "Lizon-White-Grey",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-AO-LZ",
    "amazon_sku": "HT-D-W-AO-LZ-4",
    "flipkart_sku": "SW-D-W-AO-LZ-4",
    "website_sku": "HT-D-W-AO-LZ-4",
    "amazon_asin": "B0GPPTDTXB",
    "flipkart_fsn": "CPTHHPYEFGBWMCAH",
    "product_family": "Lizon",
    "product_description": "Lizon-White-American Oak",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-WH-LZ",
    "amazon_sku": "HT-D-B-WH-LZ-4",
    "flipkart_sku": "HT-D-B-WH-LZ-4",
    "website_sku": "HT-D-B-WH-LZ-4",
    "amazon_asin": "B0FY2R2SP1",
    "flipkart_fsn": "CPTHKE3J7RSFHDTN",
    "product_family": "Lizon",
    "product_description": "Lizon-Black-White",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-NH-LZ",
    "amazon_sku": "HT-D-B-NH-LZ-4",
    "flipkart_sku": "SW-D-B-NH-LZ-4",
    "website_sku": "HT-D-B-NH-LZ-4",
    "amazon_asin": "B0GPQ19RLH",
    "flipkart_fsn": "CPTHHPV39H6KJBFZ",
    "product_family": "Lizon",
    "product_description": "Lizon-Black-Natural Ash",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-GR-LZ",
    "amazon_sku": "HT-D-B-GR-LZ-4",
    "flipkart_sku": "SW-D-B-GR-LZ-4",
    "website_sku": "HT-D-B-GR-LZ-4",
    "amazon_asin": "B0FY2QP4ZC",
    "flipkart_fsn": "CPTHKE3JZFZRKNPJ",
    "product_family": "Lizon",
    "product_description": "Lizon-Black-Grey-4",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-AO-LZ",
    "amazon_sku": "HT-D-B-AO-LZ-4",
    "flipkart_sku": "SW-D-B-AO-LZ-4",
    "website_sku": "HT-D-B-AO-LZ-4",
    "amazon_asin": "B0GPPN1X5F",
    "flipkart_fsn": "CPTHHPYJYUYSEGMM",
    "product_family": "Lizon",
    "product_description": "Lizon-Black-American Oak",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-LG-5",
    "amazon_sku": "HT-M-QB-B-LG-5x6",
    "flipkart_sku": "HT-M-QB-B-LG-5x6",
    "website_sku": "HT-M-QB-B-LG-5x6",
    "amazon_asin": "B0FTZGCPKN",
    "flipkart_fsn": "BDDHGFTQG9ATHMJK",
    "product_family": "Linea Grey",
    "product_description": "Linea Grey-Metal-Black-5X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-W-BL-HB-3",
    "amazon_sku": "HT-MB-W-HB-36",
    "flipkart_sku": "HT-MB-W-HB-36",
    "website_sku": "Metal(W)(HB) 3",
    "amazon_asin": "B0CS2VJGZH",
    "flipkart_fsn": "BDDGXC2JYZMVGGCC",
    "product_family": "Jasper",
    "product_description": "Jasper-Metal-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-HB-3",
    "amazon_sku": "HT-MB-B-HB-36",
    "flipkart_sku": "HT-MB-B-HB-36",
    "website_sku": "Metal(B)(HB) 3",
    "amazon_asin": "B0DQL2WWY6",
    "flipkart_fsn": "BDDGXC2JSPG29JHF",
    "product_family": "Jasper",
    "product_description": "Jasper-Metal-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-W-BL-HB-3",
    "amazon_sku": "HT-S-B-W-HB-2IN(3L)-36",
    "flipkart_sku": "HT-S-B-W-HB-2IN(3L)-36",
    "website_sku": "HT-S-B-W-HB-2IN(3L)-36",
    "amazon_asin": "B0DQKZJV4S",
    "flipkart_fsn": "BDDHDCHCSDUTAH3M",
    "product_family": "Jasper",
    "product_description": "Jasper-Ortho Tri-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-HB-3",
    "amazon_sku": "HT-S-B-B-HB-2IN(3L)-36",
    "flipkart_sku": "HT-S-B-B-HB-2IN(3L)-36",
    "website_sku": "HT-S-B-B-HB-2IN(3L)-36",
    "amazon_asin": "B0DQL2Z4W1",
    "flipkart_fsn": "BDDHD98JCBEM5GZ6",
    "product_family": "Jasper",
    "product_description": "Jasper-Ortho Tri-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BL-HB-3",
    "amazon_sku": "HT-S-W-B-HB-2IN-36",
    "flipkart_sku": "HT-S-W-B-HB-2IN-36",
    "website_sku": "2in Square(HB)(W)",
    "amazon_asin": "B0CS35HL9D",
    "flipkart_fsn": "BDDGXC2ZHSZ8K4Z2",
    "product_family": "Jasper",
    "product_description": "Jasper-Double Layer-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HB-3",
    "amazon_sku": "HT-S-B-B-HB-2IN-36",
    "flipkart_sku": "HT-S-B-B-HB-2IN-36",
    "website_sku": "2in Square(HB)(B)",
    "amazon_asin": "B0CS396ZXV",
    "flipkart_fsn": "BDDGXBYNGQAHGNCY",
    "product_family": "Jasper",
    "product_description": "Jasper-Double Layer-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BL-HB-3",
    "amazon_sku": "HT-S-W-B-HB-1IN-36",
    "flipkart_sku": "HT-S-W-B-HB-1IN-36",
    "website_sku": "1in Square(HB)(W)",
    "amazon_asin": "B0CS358PM9",
    "flipkart_fsn": "BDDGXC2ZQYYKSMJA",
    "product_family": "Jasper",
    "product_description": "Jasper-Single Layer-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BL-HB-3",
    "amazon_sku": "HT-S-B-B-HB-1IN-36",
    "flipkart_sku": "HT-S-B-B-HB-1IN-36",
    "website_sku": "1in Square(HB)(B)",
    "amazon_asin": "B0CS2ZFLJZ",
    "flipkart_fsn": "BDDGXC2BZJQTD5DU",
    "product_family": "Jasper",
    "product_description": "Jasper-Single Layer-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "SB-SC-BL-B",
    "amazon_sku": "HT-SC-BL-B",
    "flipkart_sku": "HT-SC-BL-B",
    "website_sku": "HT-SC-BL-B",
    "amazon_asin": "B09HMSHSJ7",
    "flipkart_fsn": "OSCG7UAZZJ2EQYZS",
    "product_family": "Eva",
    "product_description": "Eva-Black-SC",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-M3-5",
    "amazon_sku": "SW-B-BL-HW3-5",
    "flipkart_sku": "HT-QB-B-M3-WM-5x6",
    "website_sku": "HT-QB-B-M3-WM-5X6",
    "amazon_asin": "B0F4RKGV16",
    "flipkart_fsn": "BDDHCBFFGBVWQMWR",
    "product_family": "Elvo",
    "product_description": "Elvo-Metal-Wenge Black-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-M2-5",
    "amazon_sku": "SW-B-BL-HW2-5",
    "flipkart_sku": "HT-QB-B-M2-WM-5x6",
    "website_sku": "HT-QB-B-M2-WM-5X6",
    "amazon_asin": "B0F4RLXCBQ",
    "flipkart_fsn": "BDDH9QMZ7ZQJNYTZ",
    "product_family": "Elvo",
    "product_description": "Elvo-Metal-Stone Grain-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-M1-5",
    "amazon_sku": "SW-B-BL-HW1-5",
    "flipkart_sku": "HT-QB-B-M1-WM-5x6",
    "website_sku": "HT-QB-B-M1-WM-5X6",
    "amazon_asin": "B0F4RLCD5L",
    "flipkart_fsn": "BDDH9QMZRJHUFZ7V",
    "product_family": "Elvo",
    "product_description": "Elvo-Metal-American Oak-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-HW3-5",
    "amazon_sku": "SW-3L-B-BL-HW3-5",
    "flipkart_sku": "SW-3L-B-BL-HW3-5",
    "website_sku": "3L-B-BL-HW3-5",
    "amazon_asin": "B0F91HT53P",
    "flipkart_fsn": "BDDHERZZJJJ7QFXQ",
    "product_family": "Elvo",
    "product_description": "Elvo-Ortho Tri-Wenge Black-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-HW2-5",
    "amazon_sku": "SW-3L-B-BL-HW2-5",
    "flipkart_sku": "SW-3L-B-BL-HW2-5",
    "website_sku": "3L-B-BL-HW2-5",
    "amazon_asin": "B0F91KC1P3",
    "flipkart_fsn": "BDDHEPSHZDTQWAHP",
    "product_family": "Elvo",
    "product_description": "Elvo-Ortho Tri-Stone Grain-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-HW1-5",
    "amazon_sku": "SW-3L-B-BL-HW1-5",
    "flipkart_sku": "SW-3L-B-BL-HW1-5",
    "website_sku": "3L-B-BL-HW1-5",
    "amazon_asin": "B0F91KQGRB",
    "flipkart_fsn": "BDDHEPSHPVNG5XFG",
    "product_family": "Elvo",
    "product_description": "Elvo-Ortho Tri-American Oak-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HW3-5",
    "amazon_sku": "SW-2L-B-BL-HW3-5",
    "flipkart_sku": "HT-QB-2L-B-M3-WM-5x6",
    "website_sku": "2L-B-BL-HW3-5",
    "amazon_asin": "B0F91KM2CW",
    "flipkart_fsn": "BDDHCCFYC9DWRFDX",
    "product_family": "Elvo",
    "product_description": "Elvo-Double Layer-Wenge Black-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HW2-5",
    "amazon_sku": "SW-2L-B-BL-HW2-5",
    "flipkart_sku": "HT-QB-2L-B-M2-WM-5x6",
    "website_sku": "2L-B-BL-HW2-5",
    "amazon_asin": "B0F91K5YTL",
    "flipkart_fsn": "BDDHCCFYHGNYCYAT",
    "product_family": "Elvo",
    "product_description": "Elvo-Double Layer-Stone Grain-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-HW1-5",
    "amazon_sku": "SW-2L-B-BL-HW1-5",
    "flipkart_sku": "HT-QB-2L-B-M1-WM-5x6",
    "website_sku": "2L-B-BL-HW1-5",
    "amazon_asin": "B0F91KHY92",
    "flipkart_fsn": "BDDHCCFY5ZGVGMXB",
    "product_family": "Elvo",
    "product_description": "Elvo-Double Layer-American Oak-Black-5x6.5",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-WH-DU",
    "amazon_sku": "HT-D-W-WH-DU-4",
    "flipkart_sku": "SW-D-W-WH-DU-4",
    "website_sku": "HT-D-W-WH-DU-4",
    "amazon_asin": "B0FY2WJ8T9",
    "flipkart_fsn": "CPTHHF2DHSKMHJGH",
    "product_family": "Duke",
    "product_description": "Duke-White-White",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-NH-DU",
    "amazon_sku": "HT-D-W-NH-DU-4",
    "flipkart_sku": "SWB-D-WH-NH-DU-4",
    "website_sku": "HT-D-W-NH-DU-4",
    "amazon_asin": "B0GPKRFFXQ",
    "flipkart_fsn": "CPTHHXHWJDVJKWQU",
    "product_family": "Duke",
    "product_description": "Duke-White-Natural Ash",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-GR-DU",
    "amazon_sku": "HT-D-W-GR-DU-4",
    "flipkart_sku": "SW-D-W-GR-DU-4",
    "website_sku": "HT-D-W-GR-DU-4",
    "amazon_asin": "B0FY2V6S9P",
    "flipkart_fsn": "CPTHHEUHGHJUKHU3",
    "product_family": "Duke",
    "product_description": "Duke-White-Grey",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-W-AO-DU",
    "amazon_sku": "HT-D-W-AO-DU-4",
    "flipkart_sku": "SWB-D-WH-AO-DU-4",
    "website_sku": "HT-D-W-AO-DU-4",
    "amazon_asin": "B0GPLWL2TX",
    "flipkart_fsn": "CPTHM335YSPHJ9GC",
    "product_family": "Duke",
    "product_description": "Duke-White-American Oak",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-WH-DU",
    "amazon_sku": "HT-D-B-WH-DU-4",
    "flipkart_sku": "SW-D-B-WH-DU-4",
    "website_sku": "HT-D-B-WH-DU-4",
    "amazon_asin": "B0FY2VSK47",
    "flipkart_fsn": "CPTHHEUXUZCASGDH",
    "product_family": "Duke",
    "product_description": "Duke-Black-White",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-NH-DU",
    "amazon_sku": "HT-D-B-NH-DU-4",
    "flipkart_sku": "SWB-D-B-NH-DU-4",
    "website_sku": "HT-D-B-NH-DU-4",
    "amazon_asin": "B0GPKNG383",
    "flipkart_fsn": "CPTHM2XWVGQ2MUNT",
    "product_family": "Duke",
    "product_description": "Duke-Black-Natural Ash",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-GR-DU",
    "amazon_sku": "HT-D-B-GR-DU-4",
    "flipkart_sku": "HT-D-B-GR-DU-4",
    "website_sku": "HT-D-B-GR-DU-4",
    "amazon_asin": "B0FY2WFL29",
    "flipkart_fsn": "CPTHK8F5HATVRFKR",
    "product_family": "Duke",
    "product_description": "Duke-Black-Grey",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "(4)-D-B-AO-DU",
    "amazon_sku": "HT-D-B-AO-DU-4",
    "flipkart_sku": "SWB-D-B-AO-DU-4",
    "website_sku": "HT-D-B-AO-DU-4",
    "amazon_asin": "B0GPL1XBSB",
    "flipkart_fsn": "CPTHM3FKHAZUGE6R",
    "product_family": "Duke",
    "product_description": "Duke-Black-American Oak",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-G-BL-CS-6",
    "amazon_sku": "SW-G-B-CS-M-6x6.25",
    "flipkart_sku": "SW-G-B-CS-M-6x6.25",
    "website_sku": "HT-KBM-G-B-CS-6x6",
    "amazon_asin": "B0FD8TWWGX",
    "flipkart_fsn": "BDDHD9JCHFUV7JUT",
    "product_family": "Boston",
    "product_description": "Boston-Metal-Golden-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-G-BL-CS-5",
    "amazon_sku": "SW-G-B-CS-M-5x6.25",
    "flipkart_sku": "HT-QBM-G-B-CS-5x6",
    "website_sku": "HT-QBM-G-B-CS-5x6",
    "amazon_asin": "B0F6NKSLZ3",
    "flipkart_fsn": "BDDH59SRD5JPVDT8",
    "product_family": "Boston",
    "product_description": "Boston-Metal-Golden-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-G-BL-CS-4",
    "amazon_sku": "SW-G-B-CS-M-4x6.25",
    "flipkart_sku": "HT-DBM-G-B-CS-4x6",
    "website_sku": "HT-DBM-G-B-CS-4x6",
    "amazon_asin": "B0F6NML6S1",
    "flipkart_fsn": "BDDH8WWFKD78KFYC",
    "product_family": "Boston",
    "product_description": "Boston-Metal-Golden-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-G-BL-CS-6",
    "amazon_sku": "SW-G-B-CS-3L-6x6.25",
    "flipkart_sku": "SW-G-B-CS-3L-6x6.25",
    "website_sku": "SW-G-B-CS-3L-6x6.25",
    "amazon_asin": "B0FD8RYWHR",
    "flipkart_fsn": "BDDHDBEPGBFAUSFM",
    "product_family": "Boston",
    "product_description": "Boston-Ortho Tri-Golden-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-G-BL-CS-5",
    "amazon_sku": "SW-G-B-CS-3L-5x6.25",
    "flipkart_sku": "HT-QB-G-B-CS-5x6",
    "website_sku": "HT-QB-G-B-CS-5x6",
    "amazon_asin": "B0F6NH2MH7",
    "flipkart_fsn": "BDDH5Z5CXQHBMUMD",
    "product_family": "Boston",
    "product_description": "Boston-Ortho Tri-Golden-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-G-BL-CS-4",
    "amazon_sku": "SW-G-B-CS-3L-4x6.25",
    "flipkart_sku": "HT-DB-G-B-CS-4x6",
    "website_sku": "SW-G-B-CS-3L-4x6.25",
    "amazon_asin": "B0F6NK5H9H",
    "flipkart_fsn": "BDDH8WSFJGRKCQTQ",
    "product_family": "Boston",
    "product_description": "Boston-Ortho Tri-Golden-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-G-BL-CS-6",
    "amazon_sku": "SW-G-B-CS-2L-6x6.25",
    "flipkart_sku": "SW-G-B-CS-2L-6x6.25",
    "website_sku": "SW-G-B-CS-2L-6x6.25",
    "amazon_asin": "B0FD8QXVGL",
    "flipkart_fsn": "BDDHD9HP2WNUABKC",
    "product_family": "Boston",
    "product_description": "Boston-Double Layer-Golden-6x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-G-BL-CS-5",
    "amazon_sku": "SW-G-B-CS-2L-5x6.25",
    "flipkart_sku": "SW-G-B-CS-2L-5x6.25",
    "website_sku": "SW-G-B-CS-2L-5x6.25",
    "amazon_asin": "B0F6NKCF97",
    "flipkart_fsn": "BDDHEKF9KRKEHM9R",
    "product_family": "Boston",
    "product_description": "Boston-Double Layer-Golden-5x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-G-BL-CS-4",
    "amazon_sku": "SW-G-B-CS-2L-4x6.25",
    "flipkart_sku": "SW-G-B-CS-2L-4x6.25",
    "website_sku": "SW-G-B-CS-2L-4x6.25",
    "amazon_asin": "B0F6NJ4V18",
    "flipkart_fsn": "BDDHEKY2H54PHTFK",
    "product_family": "Boston",
    "product_description": "Boston-Double Layer-Golden-4x6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-BL-BL-BS-5",
    "amazon_sku": "HT-M-BS-BL-BL-5",
    "flipkart_sku": "HT-M-BS-BL-BL-5",
    "website_sku": "HT-M-BS-BL-BL-5",
    "amazon_asin": "B0GC5L7LFD",
    "flipkart_fsn": "BDDHJCB9GDBE2TEP",
    "product_family": "Base",
    "product_description": "Base-Metal-Black-5X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-BL-BL-BS-4",
    "amazon_sku": "HT-M-BS-BL-BL-4",
    "flipkart_sku": "HT-M-BS-BL-BL-4",
    "website_sku": "HT-M-BS-BL-BL-4",
    "amazon_asin": "B0GN3M8PQ2",
    "flipkart_fsn": "BDDHKMRJN8YBWAKX",
    "product_family": "Base",
    "product_description": "Base-Metal-Black-4X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-BL-BL-BS-5",
    "amazon_sku": "HT-2L-BS-BL-BL-5",
    "flipkart_sku": "HT-2L-BS-BL-BL-5",
    "website_sku": "HT-2L-BS-BL-BL-5",
    "amazon_asin": "B0GC6XCT18",
    "flipkart_fsn": "BDDHJ8S6W2TKTZR4",
    "product_family": "Base",
    "product_description": "Base-Double Layer-Black-5X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-BL-BL-BS-4",
    "amazon_sku": "HT-2L-BS-BL-BL-4",
    "flipkart_sku": "HT-2L-BS-BL-BL-4",
    "website_sku": "HT-2L-BS-BL-BL-4",
    "amazon_asin": "B0GN43W95H",
    "flipkart_fsn": "BDDHKMPHGFM8GHVR",
    "product_family": "Base",
    "product_description": "Base-Double Layer-Black-4X6.25",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-W-BL-MB-3",
    "amazon_sku": "HTMD-3x6W",
    "flipkart_sku": "MMIVF-3x6",
    "website_sku": "Metal(W) 3",
    "amazon_asin": "B093S4MKSC",
    "flipkart_fsn": "BDDG2MPGZMCERHQA",
    "product_family": "Avon",
    "product_description": "Avon-Metal-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-W-BL-MB-2",
    "amazon_sku": "HTMD-2.5x6W",
    "flipkart_sku": "MMIVF-2.5x6",
    "website_sku": "Metal(W) 2.5",
    "amazon_asin": "B093S54CT4",
    "flipkart_fsn": "BDDG42TEYMHB7MQE",
    "product_family": "Avon",
    "product_description": "Avon-Metal-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-MB-3",
    "amazon_sku": "HTMD-3x6BL",
    "flipkart_sku": "MMBF-3x6",
    "website_sku": "Metal(B) 3",
    "amazon_asin": "B08X16Y354",
    "flipkart_fsn": "BDDGFKZCDTWGT5CV",
    "product_family": "Avon",
    "product_description": "Avon-Metal-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "ME-B-BL-MB-2",
    "amazon_sku": "HTMD-2.5x6BL",
    "flipkart_sku": "MMF-2.5x6",
    "website_sku": "Metal(B) 2.5",
    "amazon_asin": "B08WZ3PTDL",
    "flipkart_fsn": "BDDGFHC4F8UG8JZF",
    "product_family": "Avon",
    "product_description": "Avon-Metal-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-VV-RF-3",
    "amazon_sku": "HT-GD-VV-BL-B-36",
    "flipkart_sku": "HT-GD-VV-BL-B-36",
    "website_sku": "HT-VV-3",
    "amazon_asin": "B09HMRHZB6",
    "flipkart_fsn": "BDDG8KZ2NZZJVP8Y",
    "product_family": "Aura",
    "product_description": "Aura-Single Layer-Velvet Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BS-RF-3",
    "amazon_sku": "HT-GD-SQ-BL-B-36",
    "flipkart_sku": "HT-GD-SQ-BL-B-36",
    "website_sku": "HT-BL-SQ-3",
    "amazon_asin": "B09HMP2N34",
    "flipkart_fsn": "BDDG7U4YASXEJNJT",
    "product_family": "Aura",
    "product_description": "Aura-Single Layer-Blue Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BR-GD-3",
    "amazon_sku": "HTMM-3x6BL",
    "flipkart_sku": "HT-GD-SQ-BR-36",
    "website_sku": "HT-Br-SQ-3",
    "amazon_asin": "B08X15K631",
    "flipkart_fsn": "BDDGABZXJTNCGMW5",
    "product_family": "Aura",
    "product_description": "Aura-Single Layer-Brown Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-RF-3",
    "amazon_sku": "HT-R-B-B-36-2IN(3L)",
    "flipkart_sku": "HT-R-B-B-36-2IN(3L)",
    "website_sku": "HT-R-B-B-36-2IN(3L)",
    "amazon_asin": "B0GKV73ZFV",
    "flipkart_fsn": "BDDHKD47MMPHWJX8",
    "product_family": "Atlas",
    "product_description": "Atlas-Ortho Tri-Black-3X6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-RF-2",
    "amazon_sku": "HT-R-B-B-256-2IN(3L)",
    "flipkart_sku": "HT-R-B-B-256-2IN(3L)",
    "website_sku": "HT-R-B-B-256-2IN(3L)",
    "amazon_asin": "B0GKVLW7KR",
    "flipkart_fsn": "BDDHKBKZHZTQFZJP",
    "product_family": "Atlas",
    "product_description": "Atlas-Ortho Tri-Black-2.5X6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BR-RF-3",
    "amazon_sku": "HT-R-W-BR-36-2IN",
    "flipkart_sku": "HT-R-W-BR-36-2IN",
    "website_sku": "HT-R-W-BR-36-2IN",
    "amazon_asin": "B0CTTN1C5D",
    "flipkart_fsn": "BDDGXQFGSJHFTZKY",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Brown Mattress-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BR-RF-2",
    "amazon_sku": "HT-R-W-BR-256-2IN",
    "flipkart_sku": "HT-R-W-BR-256-2IN",
    "website_sku": "HT-R-W-BR-256-2IN",
    "amazon_asin": "B0CTTS94C5",
    "flipkart_fsn": "BDDGXQFGTUYRMQZU",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Brown Mattress-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BL-RF-3",
    "amazon_sku": "HT-R-B-W-36-2IN",
    "flipkart_sku": "HT-R-B-W-36-2IN",
    "website_sku": "2in Black (W) 3",
    "amazon_asin": "B09ZDYB4PP",
    "flipkart_fsn": "BDDGEYNGGGQFTF63",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Black Mattress-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BL-RF-2",
    "amazon_sku": "HT-R-B-W-256-2IN",
    "flipkart_sku": "HT-R-B-W-256-2IN",
    "website_sku": "2in Black (W) 2.5",
    "amazon_asin": "B09ZDM9HZK",
    "flipkart_fsn": "BDDGEYZFGKYRWQQJ",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Black Mattress-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BR-RF-3",
    "amazon_sku": "HT-R-B-BR-36-2IN",
    "flipkart_sku": "HT-R-BR-B-3x6-2IN",
    "website_sku": "HT-R-B-BR-36-2IN",
    "amazon_asin": "B0C154X9KG",
    "flipkart_fsn": "BDDGZZZW7RHDBUZR",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Brown Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BR-RF-2",
    "amazon_sku": "HT-R-B-BR-256-2IN",
    "flipkart_sku": "HT-R-BR-b-2.5x6-2IN",
    "website_sku": "HT-R-B-BR-256-2IN",
    "amazon_asin": "B0C1551PH2",
    "flipkart_fsn": "BDDGPJXSZRZV2FFC",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Brown Mattress-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-RF-3",
    "amazon_sku": "HT-R-B-B-36-2IN",
    "flipkart_sku": "HT-R-B-B-36-2IN",
    "website_sku": "2in Black 3",
    "amazon_asin": "B09Z6CZFPQ",
    "flipkart_fsn": "BDDGDVXGNXA9685G",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Black Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-RF-2",
    "amazon_sku": "HT-R-B-B-256-2IN",
    "flipkart_sku": "HT-R-B-B-256-2",
    "website_sku": "2in Black 2.5",
    "amazon_asin": "B09Z5L76CX",
    "flipkart_fsn": "BDDGEVHXCGGWMAKQ",
    "product_family": "Atlas",
    "product_description": "Atlas-Double Layer-Black Mattress-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BR-RF-3",
    "amazon_sku": "HT-R-W-BR-36-1IN",
    "flipkart_sku": "HT-R-W-BR-36-1IN",
    "website_sku": "HT-R-W-BR-36-1IN",
    "amazon_asin": "B0CTTMGL99",
    "flipkart_fsn": "BDDGXQFGDKREHRXW",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Brown Mattress-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BR-RF-2",
    "amazon_sku": "HT-R-W-BR-256-1IN",
    "flipkart_sku": "HT-R-W-BR-256-1IN",
    "website_sku": "HT-R-W-BR-256-1IN",
    "amazon_asin": "B0CTT8R5J8",
    "flipkart_fsn": "BDDGXQFGDAKFCVCJ",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Brown Mattress-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BL-RF-3",
    "amazon_sku": "HT-R-B-W-36-1IN",
    "flipkart_sku": "HT-R-B-W-36-1IN",
    "website_sku": "1in Black (W) 3",
    "amazon_asin": "B09ZDRHZ1P",
    "flipkart_fsn": "BDDGEYN3YKJXHCKC",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Black Mattress-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-W-BL-RF-2",
    "amazon_sku": "HT-R-B-W-256-1IN",
    "flipkart_sku": "HT-R-B-W-256-1IN",
    "website_sku": "1in Black (W) 2.5",
    "amazon_asin": "B09ZDLR7B7",
    "flipkart_fsn": "BDDGEYNZBBGWFAU2",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Black Mattress-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BR-RF-3",
    "amazon_sku": "HT-R-B-BR-36-1IN",
    "flipkart_sku": "HT-R-BR-B-3x6-1IN",
    "website_sku": "HT-R-B-BR-36-1IN",
    "amazon_asin": "B0C1577QXY",
    "flipkart_fsn": "BDDGPF3RZ3WTMVFS",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Brown Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BR-RF-2",
    "amazon_sku": "HT-R-B-BR-256-1IN",
    "flipkart_sku": "HT-R-B-BR-2.5x6-1IN",
    "website_sku": "HT-R-B-BR-256-1IN",
    "amazon_asin": "B0C156XKX1",
    "flipkart_fsn": "BDDGZZZKBQ4H8YPY",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Brown Mattress-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BL-RF-3",
    "amazon_sku": "HT-R-B-B-36-1IN",
    "flipkart_sku": "HT-R-B-B-36-1IN",
    "website_sku": "1in Black 3",
    "amazon_asin": "B09Z64PX66",
    "flipkart_fsn": "BDDGDY54YHFKSZPH",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Black Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L1-B-BL-RF-2",
    "amazon_sku": "HT-R-B-B-256-1IN",
    "flipkart_sku": "HT-R-b-b-256-1IN",
    "website_sku": "1in Black 2.5",
    "amazon_asin": "B09Z68QKPC",
    "flipkart_fsn": "BDDGENQUJFM6R5GZ",
    "product_family": "Atlas",
    "product_description": "Atlas-Single Layer-Black Mattress-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BL-NX-3",
    "amazon_sku": "HTMR-3x6(WHITE)-2L",
    "flipkart_sku": "HTMR-36(WHITE)-2L",
    "website_sku": "HTMR-3x6(WHITE)-2L",
    "amazon_asin": "B0GX21RQM4",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Double Layer-Black Mattress-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-W-BL-NX-2",
    "amazon_sku": "HTMR-2.5x6(WHITE)-2L",
    "flipkart_sku": "HTMR-2.5x6(WHITE)-2L",
    "website_sku": "HTMR-2.5x6(WHITE)-2L",
    "amazon_asin": "B0GX2BZQ22",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Double Layer-Black Mattress-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-NX-3",
    "amazon_sku": "HTMR-3x6(BLACK)-2L",
    "flipkart_sku": "HTMR-36(BLACK)-2L",
    "website_sku": "HTMR-3x6(BLACK)-2L",
    "amazon_asin": "B0GX1WH925",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Double Layer-Black Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L2-B-BL-NX-2",
    "amazon_sku": "HTMR-2.5x6(BLACK)-2L",
    "flipkart_sku": "HTMR-2.5x6(BLACK)-2L",
    "website_sku": "HTMR-2.5x6(BLACK)-2L",
    "amazon_asin": "B0GX22VRS1",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Double Layer-Black Mattress-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-W-BL-NX-3",
    "amazon_sku": "HTMR-3x6(WHITE)-3L",
    "flipkart_sku": "HTMR-3x6(WHITE)-3L",
    "website_sku": "HTMR-3x6(WHITE)-3L",
    "amazon_asin": "B0GX265DJJ",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Ortho Tri Layer-Black Mattress-White-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-W-BL-NX-2",
    "amazon_sku": "HTMR-2.5x6(WHITE)-3L",
    "flipkart_sku": "HTMR-2.5x6(WHITE)-3L",
    "website_sku": "HTMR-2.5x6(WHITE)-3L",
    "amazon_asin": "B0GX2335W7",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Ortho Tri Layer-Black Mattress-White-2.5x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-NX-3",
    "amazon_sku": "HTMR-3x6(BLACK)-3L",
    "flipkart_sku": "HTMR-3x6(BLACK)-3L",
    "website_sku": "HTMR-3x6(BLACK)-3L",
    "amazon_asin": "B0GX1YCDMX",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Ortho Tri Layer-Black Mattress-Black-3x6",
    "hsn": "",
    "gst_rate": null
  },
  {
    "master_sku": "L3-B-BL-NX-2",
    "amazon_sku": "HTMR-2.5x6(BLACK)-3L",
    "flipkart_sku": "HTMR-2.5x6(BLACK)-3L",
    "website_sku": "HTMR-2.5x6(BLACK)-3L",
    "amazon_asin": "B0GX27YJNL",
    "flipkart_fsn": "In Process",
    "product_family": "Nexon",
    "product_description": "Nexon-Ortho Tri Layer-Black Mattress-Black-2.5x6",
    "hsn": "",
    "gst_rate": null
  }
];